/**********************************************************
 * BEWARE: This file is a autogenerated stub!
 *********************************************************/

#include <stdlib.h>

#include "include/capi/cef_keyboard_handler_capi.h"

#include "cef/base.h"
#include "util.h"

CEF_CALLBACK int keyboard_handler_on_pre_key_event(struct _cef_keyboard_handler_t *self, struct _cef_browser_t *browser, const struct _cef_key_event_t *event, XEvent *os_event, int *is_keyboard_shortcut)
{
	static const char* const eventNames[] = {"RAWKEYDOWN", "KEYDOWN", "KEYUP", "CHAR"}; 

	DEBUG_PRINT("pre key event: %11s, char %c(%c), modifiers 0x%08X, native keycode %d, system key: %d, edit field %d",
		event->type < LENGTH(eventNames) ? eventNames[event->type] : "UNKNOWN", 
		event->character,
		event->unmodified_character,
		event->modifiers,
		event->native_key_code,
		event->is_system_key,
		event->focus_on_editable_field
	);
	return 0;
}

CEF_CALLBACK int keyboard_handler_on_key_event(struct _cef_keyboard_handler_t *self, struct _cef_browser_t *browser, const struct _cef_key_event_t *event, XEvent *os_event)
{
	DEBUG_ONCE("");
	return 0;
}

struct _cef_keyboard_handler_t *init_keyboard_handler()
{
	struct _cef_keyboard_handler_t *ret = NULL;
	struct refcount *r = NULL;
	char *cp = NULL;

	DEBUG_ONCE("called");
	if (!(r = calloc(sizeof(struct refcount) + sizeof(struct _cef_keyboard_handler_t), 1))) {
		DEBUG_PRINT("#### out of memory! #####");
		return NULL;
	}

	cp = (char*)r;
	cp += sizeof(struct refcount);
	ret = (struct _cef_keyboard_handler_t*)cp;

	if(!init_base((cef_base_t*)ret, sizeof(struct _cef_keyboard_handler_t))) {
		free(r);
		return NULL;
	}
	ret->base.add_ref((cef_base_t*)ret);

	// callbacks
	ret->on_pre_key_event = &keyboard_handler_on_pre_key_event;
	ret->on_key_event = &keyboard_handler_on_key_event;

	return ret;
}