/**********************************************************
 * BEWARE: This file is a autogenerated stub!
 *********************************************************/

#include <stdlib.h>
#include <string.h>

#include "include/capi/cef_v8_capi.h"

#include "cef/base.h"
#include "util.h"

CEF_CALLBACK int v8handler_execute(
	struct _cef_v8handler_t *self, 
	const cef_string_t *name, 
	struct _cef_v8value_t *object, 
	size_t argumentsCount, 
	struct _cef_v8value_t * const* arguments, 
	struct _cef_v8value_t **retval, 
	cef_string_t *exception)
{
	DEBUG_PRINT("received V8 call");

	// get the function name



	//KAI: clean up all references
	return 1;
}

struct _cef_v8handler_t *init_v8handler()
{
	struct _cef_v8handler_t *ret = NULL;
	struct refcount *r = NULL;
	char *cp = NULL;

	DEBUG_ONCE("called");
	if (!(r = calloc(sizeof(struct refcount) + sizeof(struct _cef_v8handler_t), 1))) {
		DEBUG_PRINT("#### out of memory! #####");;
		return NULL;
	}

	cp = (char*)r;
	cp += sizeof(struct refcount);
	ret = (struct _cef_v8handler_t*)cp;

	if(!init_base((cef_base_t*)ret, sizeof(struct _cef_v8handler_t))) {
		free(r);
		return NULL;
	}
	ret->base.add_ref((cef_base_t*)ret);

	// callbacks
	ret->execute = &v8handler_execute;

	return ret;
}